import {
  getCategoriesQuery,
  getSubCategoriesQuery,
  getCategoryByIdQuery,
  addCategoryQuery,
  updateCategoryQuery,
  deleteCategoryQuery,
  archivedCategoryQuery,
  addSubCategoryQuery,
  updateSubCategoryQuery,
  deleteSubCategoryQuery,
  archivedSubCategoryQuery,
  getAllSubCategoriesByCategoryIdQuery,
  getAllSubCategoriesQuery,
} from './categories/index.js';

import {
  getProductByIdQuery,
  getSingleProductReviewByIdQuery,
  getCollectReviewForProductQuery,
  getSuperDealsQuery,
  addReviewProductQuery,
  getProductsQuery,
  getRecommendedProductQuery,
  deleteProductQuery,
  archivedProductQuery,
  addProductQuery,
  updateProductQuery,
  getAllProductsByCategoryIdQuery,
  getAllProductsBySubCategoryQuery,
} from './products/index.js';

import {
  addNewUserQuery,
  checkEmailExistsQuery,
  updateInfoUserQuery,
  getUserAddressesQuery,
  addUserAddressQuery,
  deleteUserAddressQuery,
  updateUserAddressQuery,
  updateAddressDefaultQuery,
  updateUserPasswordQuery,
  updateUserResetQuery,
  checkUserByResetLinkQuery,
  updateUserResetPasswordQuery,
  getUsersAndEmployeesQuery,
} from './users/index.js';

import {
  checkGuestEmailExistsQuery,
  addGuestQuery,
} from './guests/index.js';

import {
  getUserOrdersQuery,
  getSingleOrderQuery,
  addGuestOrderQuery,
  addUserOrderQuery,
  getProductsFromOrderQuery,
  updateOrderQuery,
  getAllOrdersJoinUsersQuery,
  getAllOrdersJoinGuestsQuery,
} from './orders/index.js';

import {
  getBrandsQuery,
  addBrandsQuery,
  deleteBrandsQuery,
  updateBrandsQuery,
  archivedBrandsQuery,
} from './brands/index.js';

import {
  getUserCartsQuery,
  deleteProductFromUserCartsQuery,
  addProductToUserCartsQuery,
  updateProductQuantityQuery,
} from './carts/index.js';

import {
  getUserWishlistsQuery,
  deleteProductFromUserWishlistsQuery,
  addProductToUserWishlistsQuery,
} from './wishlists/index.js';

import {
  getBannersQuery,
  addBannerQuery,
  updateBannerQuery,
  getAllBannersQuery,
} from './banners/index.js';

import {
  addEmployeeQuery,
  getEmployeesQuery,
  getRolesQuery,
  getRolesPermissionsQuery,
  getPagesQuery,
  getPermissionsQuery,
  checkRoleExistsQuery,
  addRolesQuery,
  addRolesPermissionsQuery,
  updateRoleForEmployeeQuery,
  getOrderStatusQuery,
  getOrderByMonthQuery,
  deleteRoleQuery,
  checkUsersByRoleIdQuery,
} from './admin/index.js';

import {
  addPromoCodeQuery,
  deletePromoCodeQuery,
  checkPromoCodeExistsQuery,
  getPromoCodesQuery,
  updatePromoCodeQuery,
} from './promoCodes/index.js';

export {
  getCategoriesQuery,
  getSubCategoriesQuery,
  getProductByIdQuery,
  getSingleProductReviewByIdQuery,
  getCollectReviewForProductQuery,
  addNewUserQuery,
  checkEmailExistsQuery,
  updateInfoUserQuery,
  getUserAddressesQuery,
  addUserAddressQuery,
  deleteUserAddressQuery,
  updateUserAddressQuery,
  updateAddressDefaultQuery,
  getSuperDealsQuery,
  addReviewProductQuery,
  updateUserPasswordQuery,
  getUserOrdersQuery,
  checkGuestEmailExistsQuery,
  getSingleOrderQuery,
  addGuestQuery,
  addGuestOrderQuery,
  addUserOrderQuery,
  getBrandsQuery,
  getProductsQuery,
  getProductsFromOrderQuery,
  getUserCartsQuery,
  deleteProductFromUserCartsQuery,
  addProductToUserCartsQuery,
  updateProductQuantityQuery,
  getUserWishlistsQuery,
  deleteProductFromUserWishlistsQuery,
  addProductToUserWishlistsQuery,
  getRecommendedProductQuery,
  updateUserResetQuery,
  checkUserByResetLinkQuery,
  updateUserResetPasswordQuery,
  getCategoryByIdQuery,
  addBrandsQuery,
  deleteBrandsQuery,
  updateBrandsQuery,
  archivedBrandsQuery,
  getBannersQuery,
  addBannerQuery,
  updateBannerQuery,
  addCategoryQuery,
  updateCategoryQuery,
  deleteCategoryQuery,
  archivedCategoryQuery,
  addSubCategoryQuery,
  updateSubCategoryQuery,
  deleteSubCategoryQuery,
  archivedSubCategoryQuery,
  deleteProductQuery,
  archivedProductQuery,
  addProductQuery,
  updateProductQuery,
  addEmployeeQuery,
  getEmployeesQuery,
  getRolesQuery,
  getRolesPermissionsQuery,
  getPagesQuery,
  getPermissionsQuery,
  checkRoleExistsQuery,
  addRolesQuery,
  addRolesPermissionsQuery,
  getUsersAndEmployeesQuery,
  getAllBannersQuery,
  getAllSubCategoriesByCategoryIdQuery,
  getAllProductsByCategoryIdQuery,
  getAllProductsBySubCategoryQuery,
  getAllSubCategoriesQuery,
  updateOrderQuery,
  getAllOrdersJoinUsersQuery,
  getAllOrdersJoinGuestsQuery,
  updateRoleForEmployeeQuery,
  getOrderStatusQuery,
  getOrderByMonthQuery,
  addPromoCodeQuery,
  deletePromoCodeQuery,
  checkPromoCodeExistsQuery,
  getPromoCodesQuery,
  updatePromoCodeQuery,
  deleteRoleQuery,
  checkUsersByRoleIdQuery,
};
